# Generated by Django 5.2.17 on 2026-09-29 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteutilisateur',
            name='note_facilite',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Note de facilité d'usage (sur 5)"),
        ),
        migrations.AlterField(
            model_name='noteutilisateur',
            name='note_qualite',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note de qualité de service (sur 5)'),
        ),
    ]
