# Generated by Django 5.2.10 on 2026-05-27 15:19

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_demandeacceslectureseule'),
    ]

    operations = [
        UnaccentExtension()
    ]
