# Generated by Django 5.2.10 on 2026-06-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_auto_20260527_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='locataire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du contract de location'),
        ),
        migrations.AddField(
            model_name='ads',
            name='locataire_email',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name="Email du locataire de l'ADS"),
        ),
        migrations.AddField(
            model_name='ads',
            name='locataire_nom',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name="Nom du locataire de l'ADS (personne physique ou morale)"),
        ),
        migrations.AddField(
            model_name='ads',
            name='locataire_phone',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name="Téléphone fixe du locataire de l'ADS"),
        ),
        migrations.AddField(
            model_name='ads',
            name='locataire_siret',
            field=models.CharField(blank=True, default='', help_text="Nous validons ce numéro en consultant les données officielles de l'INSEE. Indiquez le numéro de SIRET (14 chiffres) sans espace. ", max_length=128, verbose_name="SIRET du locataire de l'ADS"),
        ),
        migrations.AddField(
            model_name='ads',
            name='location',
            field=models.BooleanField(blank=True, default=False, verbose_name="L'ADS est elle en location?"),
        ),
    ]
