# Generated by Django 5.2.10 on 2026-06-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_auto_20260527_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsmanageradministrator',
            name='notify_verification_enabled',
            field=models.BooleanField(blank=True, default=False, help_text="Si cette case est cochée, un mail sera envoyé mensuellement aux gestionnaires attachés à cette préfecture pour les notifier si au moins une de leur ADS n'est pas complète et à jour", verbose_name='Activer les notifications pour la vérification'),
        ),
    ]
