# Generated by Django 5.2.15 on 2026-07-08 11:07

import django.db.models.deletion
import mesads.common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_adsmanageradministrator_notify_verification_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeRegistreTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text="Date de suppression de l'objet. Si cette date est renseignée, l'objet est considéré comme supprimé.", null=True, verbose_name='Date de suppression')),
                ('date_transaction', models.DateField(blank=True, default=None, help_text='Date effective de la cession', null=True, verbose_name='Date de la transaction')),
                ('montant_transaction', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant en euros, hors taxes', max_digits=12, null=True, verbose_name='Montant de la transaction')),
                ('ancien_exploitant', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom - Prénom ou Dénomination sociale')),
                ('nouvel_exploitant', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom - Prénom ou Dénomination sociale')),
                ('siret_nouvel_exploitant', models.CharField(blank=True, default='', help_text='14 chiffres - Obligatoire pour les personnes morales. ', max_length=128, verbose_name='Numéro SIRET')),
                ('demande_cession', models.BooleanField(default=False, verbose_name='Demande de cession signée par le cédant')),
                ('justificatif_exploitation', models.BooleanField(default=False, verbose_name="Justificatif de l'exploitation effective et continue")),
                ('piece_identite', models.BooleanField(default=False, verbose_name="Pièce d'identité du cessionnaire")),
                ('justificatif_montant', models.BooleanField(default=False, verbose_name='Justificatif du montant de la transaction')),
                ('kbis_ou_siren', models.BooleanField(default=False, verbose_name='Extrait Kbis ou justificatif SIREN (si société)')),
                ('attestation_aptitude_professionnelle', models.BooleanField(default=False, verbose_name="Attestation d'aptitude professionnelle du cessionnaire")),
                ('justificatif_liquidation_judiciaire', models.BooleanField(default=False, verbose_name='Justificatif de la liquidation judiciaire')),
                ('autres_documents', models.BooleanField(default=False, verbose_name='Autres')),
                ('autres_documents_description', models.CharField(blank=True, default='', help_text='Précisez le(s) document(s)', max_length=255, verbose_name='Autres Documents')),
                ('documents_complet', models.BooleanField(default=False, verbose_name="Indiquez l'état du dossier en fonction des pièces sélectionnées.")),
                ('statut', models.CharField(blank=True, choices=[('brouillon', 'Brouillon'), ('enregistree', 'Enregistrée')], default='brouillon', max_length=255, verbose_name='Statut de la transaction')),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='app.ads', verbose_name='ADS')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=(mesads.common.mixins.CharFieldsStripperMixin, models.Model),
        ),
    ]
