# Generated by Django 5.2.15 on 2026-07-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_entreeregistretransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsmanager',
            name='registre_transaction_publique',
            field=models.BooleanField(default=False, help_text="Cochez cette case pour que le registre des transactions de l'administration soit publique."),
        ),
    ]
