# Generated by Django 5.2.10 on 2026-06-08 09:02

from django.db import migrations


def migrate_data_locataire(app, schema_editor):
    ADS = app.get_model("app", "ADS")
    LOCATAIRE_GERANT = "locataire_gerant"
    ads_with_locataire = ADS.objects.filter(adsuser__status=LOCATAIRE_GERANT)

    for ads in ads_with_locataire:
        users = ads.adsuser_set.filter(status=LOCATAIRE_GERANT)
        ads.location = True
        for u in users:
            if u.name and not ads.locataire_nom:
                ads.locataire_nom = u.name
            if u.siret and not ads.locataire_siret:
                ads.locataire_siret = u.siret
            if u.date_location_gerance and not ads.locataire_date:
                ads.locataire_date = u.date_location_gerance
        ads.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_adsmanageradministrator_notify_verification_enabled'),
    ]

    operations = [
        migrations.RunPython(migrate_data_locataire)
    ]
