# Generated by Django 5.2.15 on 2026-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_adsmanager_registre_transaction_publique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsmanager',
            old_name='registre_transaction_publique',
            new_name='registre_transaction_public',
        ),
        migrations.RemoveField(
            model_name='entreeregistretransaction',
            name='attestation_aptitude_professionnelle',
        ),
        migrations.RemoveField(
            model_name='entreeregistretransaction',
            name='justificatif_liquidation_judiciaire',
        ),
        migrations.RemoveField(
            model_name='entreeregistretransaction',
            name='piece_identite',
        ),
        migrations.RemoveField(
            model_name='entreeregistretransaction',
            name='siret_nouvel_exploitant',
        ),
        migrations.AddField(
            model_name='entreeregistretransaction',
            name='siren_nouvel_exploitant',
            field=models.CharField(blank=True, default='', help_text='9 chiffres - Obligatoire pour les personnes morales. ', max_length=128, verbose_name='Numéro SIREN'),
        ),
    ]
