# Generated by Django 5.2.17 on 2026-09-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0123_demandegestionprefecture_statut_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeregistretransaction',
            name='statut',
            field=models.CharField(blank=True, choices=[('brouillon', 'Brouillon'), ('brouillon_doc', 'Brouillon'), ('enregistree', 'Enregistrée')], default='brouillon_doc', max_length=255, verbose_name='Statut de la transaction'),
        ),
    ]
